server:
  port: 9007
spring:
  application:
    name: tensquare-search

  data:
    elasticsearch:
      cluster-nodes: 10.201.23.100:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true