server:
  port: 6868

eureka:
  client:
    register-with-eureka: false # 是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetch-registry: false   # 是否从Eureka中获取注册信息
    service-url: # Eureka客户端与Eureka服务端进行交互的地址
      default-zone: http://127.0.0.1:${server.port}/eureka/